### PR TITLE
Update ColorSchemeSelector.py

### PR DESCRIPTION
**Pull request by bobuk**
has_key() call was replaced with method appropriated in python3.3 (for ST3 support)
get_color_schemes method rewritten for truly recursive 'Packages' walking.
\n was added to pep8ification of source code

### CODE REVIEW

**Comment by fabiokr** [comment]
:+1:

**Comment by jugyo** [comment]
I'm sorry because I hadn't noticed this good pull request.

**Comment by sleeve** [comment]
Hmm still not working for me in ST3 on OS X. Works great in ST2 though.

**Comment by bobuk** [comment]
@sleeve it's because you use "packaged" color schemes, I think.
May I ask you to drop some color schemes to Packages directory and check it again?

**Comment by sleeve** [comment]
@bobuk You were correct sir. All of my color schemes were packaged in '.sublime-package' files. Unpacking them to the Packages directory makes this plugin function correctly. It would be great if it worked with Packaged schemes though. Thanks for the workaround.

**Pull request merged**
